# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

services:
  mongodb:
    image: ghcr.io/beshkenadze/bitnami-mongodb/mongodb:6.0
    build:
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/bitnami/mongodb"

volumes:
  mongodb_data:
    driver: local
