global:
  security:
    ## @param global.security.allowInsecureImages Allows skipping image verification
    allowInsecureImages: true
image:
  registry: docker.io
  repository: beshkenadze/bitnami-mongodb
  tag: "6.0.9"
  digest: ""
